### ISSUE TITLE
Time button is broken

### ISSUE THREAD

**Issue by tilsche** [metricq/metricq-webview#193]
Since the recent update, the time button appears to be broken - no reaction when clicking it.

```
jquery.js:4050 jQuery.Deferred exception: Cannot read properties of undefined (reading 'instances') TypeError: Cannot read properties of undefined (reading 'instances')
    at HTMLDocument.<anonymous> (https://metricq.zih.tu-dresden.de/webview/js/app.556cbaf7.js:1:92160)
    at l (https://metricq.zih.tu-dresden.de/webview/js/chunk-vendors.aad772e7.js:117:26388)
    at c (https://metricq.zih.tu-dresden.de/webview/js/chunk-vendors.aad772e7.js:117:26693) undefined
C.Deferred.exceptionHook @ jquery.js:4050
jquery.js:4059 Uncaught TypeError: Cannot read properties of undefined (reading 'instances')
    at HTMLDocument.<anonymous> (time-button.vue:51:1)
    at l (jquery.js:3766:29)
    at c (jquery.js:3834:12)
```

**Comment by tilsche** [comment]
Does not affect firefox.
Was introduced somewhere between 9f1a761 and 8cf8d36
